//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.DataModal.Entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Weather", Namespace="http://schemas.datacontract.org/2004/07/CS.DataModal.Entities")]
    public partial class Weather : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _allergyField;
        
        private bool _bIsChangedField;
        
        private bool _bIsDeletedField;
        
        private string _carcleanField;
        
        private string _clothesField;
        
        private string _clothes48Field;
        
        private string _clothes48dField;
        
        private string _clothesdField;
        
        private string _comfortField;
        
        private System.Nullable<System.DateTime> _dateField;
        
        private string _fl1Field;
        
        private string _fl2Field;
        
        private string _fl3Field;
        
        private string _fl4Field;
        
        private string _fl5Field;
        
        private string _fl6Field;
        
        private string _fx1Field;
        
        private string _fx2Field;
        
        private string _morningexerciseField;
        
        private int _recidField;
        
        private string _suncuringField;
        
        private System.Nullable<int> _temp11Field;
        
        private System.Nullable<int> _temp12Field;
        
        private System.Nullable<int> _temp21Field;
        
        private System.Nullable<int> _temp22Field;
        
        private System.Nullable<int> _temp31Field;
        
        private System.Nullable<int> _temp32Field;
        
        private System.Nullable<int> _temp41Field;
        
        private System.Nullable<int> _temp42Field;
        
        private System.Nullable<int> _temp51Field;
        
        private System.Nullable<int> _temp52Field;
        
        private System.Nullable<int> _temp61Field;
        
        private System.Nullable<int> _temp62Field;
        
        private string _tourField;
        
        private string _ultravioletField;
        
        private string _ultraviolet48Field;
        
        private string _urlField;
        
        private string _weather1Field;
        
        private string _weather2Field;
        
        private string _weather3Field;
        
        private string _weather4Field;
        
        private string _weather5Field;
        
        private string _weather6Field;
        
        private string _wind1Field;
        
        private string _wind2Field;
        
        private string _wind3Field;
        
        private string _wind4Field;
        
        private string _wind5Field;
        
        private string _wind6Field;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _allergy
        {
            get
            {
                return this._allergyField;
            }
            set
            {
                this._allergyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _bIsChanged
        {
            get
            {
                return this._bIsChangedField;
            }
            set
            {
                this._bIsChangedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _bIsDeleted
        {
            get
            {
                return this._bIsDeletedField;
            }
            set
            {
                this._bIsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _carclean
        {
            get
            {
                return this._carcleanField;
            }
            set
            {
                this._carcleanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _clothes
        {
            get
            {
                return this._clothesField;
            }
            set
            {
                this._clothesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _clothes48
        {
            get
            {
                return this._clothes48Field;
            }
            set
            {
                this._clothes48Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _clothes48d
        {
            get
            {
                return this._clothes48dField;
            }
            set
            {
                this._clothes48dField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _clothesd
        {
            get
            {
                return this._clothesdField;
            }
            set
            {
                this._clothesdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _comfort
        {
            get
            {
                return this._comfortField;
            }
            set
            {
                this._comfortField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _date
        {
            get
            {
                return this._dateField;
            }
            set
            {
                this._dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _fl1
        {
            get
            {
                return this._fl1Field;
            }
            set
            {
                this._fl1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _fl2
        {
            get
            {
                return this._fl2Field;
            }
            set
            {
                this._fl2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _fl3
        {
            get
            {
                return this._fl3Field;
            }
            set
            {
                this._fl3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _fl4
        {
            get
            {
                return this._fl4Field;
            }
            set
            {
                this._fl4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _fl5
        {
            get
            {
                return this._fl5Field;
            }
            set
            {
                this._fl5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _fl6
        {
            get
            {
                return this._fl6Field;
            }
            set
            {
                this._fl6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _fx1
        {
            get
            {
                return this._fx1Field;
            }
            set
            {
                this._fx1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _fx2
        {
            get
            {
                return this._fx2Field;
            }
            set
            {
                this._fx2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _morningexercise
        {
            get
            {
                return this._morningexerciseField;
            }
            set
            {
                this._morningexerciseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _recid
        {
            get
            {
                return this._recidField;
            }
            set
            {
                this._recidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _suncuring
        {
            get
            {
                return this._suncuringField;
            }
            set
            {
                this._suncuringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _temp11
        {
            get
            {
                return this._temp11Field;
            }
            set
            {
                this._temp11Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _temp12
        {
            get
            {
                return this._temp12Field;
            }
            set
            {
                this._temp12Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _temp21
        {
            get
            {
                return this._temp21Field;
            }
            set
            {
                this._temp21Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _temp22
        {
            get
            {
                return this._temp22Field;
            }
            set
            {
                this._temp22Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _temp31
        {
            get
            {
                return this._temp31Field;
            }
            set
            {
                this._temp31Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _temp32
        {
            get
            {
                return this._temp32Field;
            }
            set
            {
                this._temp32Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _temp41
        {
            get
            {
                return this._temp41Field;
            }
            set
            {
                this._temp41Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _temp42
        {
            get
            {
                return this._temp42Field;
            }
            set
            {
                this._temp42Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _temp51
        {
            get
            {
                return this._temp51Field;
            }
            set
            {
                this._temp51Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _temp52
        {
            get
            {
                return this._temp52Field;
            }
            set
            {
                this._temp52Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _temp61
        {
            get
            {
                return this._temp61Field;
            }
            set
            {
                this._temp61Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _temp62
        {
            get
            {
                return this._temp62Field;
            }
            set
            {
                this._temp62Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _tour
        {
            get
            {
                return this._tourField;
            }
            set
            {
                this._tourField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ultraviolet
        {
            get
            {
                return this._ultravioletField;
            }
            set
            {
                this._ultravioletField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ultraviolet48
        {
            get
            {
                return this._ultraviolet48Field;
            }
            set
            {
                this._ultraviolet48Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _url
        {
            get
            {
                return this._urlField;
            }
            set
            {
                this._urlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _weather1
        {
            get
            {
                return this._weather1Field;
            }
            set
            {
                this._weather1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _weather2
        {
            get
            {
                return this._weather2Field;
            }
            set
            {
                this._weather2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _weather3
        {
            get
            {
                return this._weather3Field;
            }
            set
            {
                this._weather3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _weather4
        {
            get
            {
                return this._weather4Field;
            }
            set
            {
                this._weather4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _weather5
        {
            get
            {
                return this._weather5Field;
            }
            set
            {
                this._weather5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _weather6
        {
            get
            {
                return this._weather6Field;
            }
            set
            {
                this._weather6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _wind1
        {
            get
            {
                return this._wind1Field;
            }
            set
            {
                this._wind1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _wind2
        {
            get
            {
                return this._wind2Field;
            }
            set
            {
                this._wind2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _wind3
        {
            get
            {
                return this._wind3Field;
            }
            set
            {
                this._wind3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _wind4
        {
            get
            {
                return this._wind4Field;
            }
            set
            {
                this._wind4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _wind5
        {
            get
            {
                return this._wind5Field;
            }
            set
            {
                this._wind5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _wind6
        {
            get
            {
                return this._wind6Field;
            }
            set
            {
                this._wind6Field = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWCFWeatherService")]
public interface IWCFWeatherService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFWeatherService/GetWeather", ReplyAction="http://tempuri.org/IWCFWeatherService/GetWeatherResponse")]
    CS.DataModal.Entities.Weather GetWeather(string ip);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFWeatherService/Get600CDay", ReplyAction="http://tempuri.org/IWCFWeatherService/Get600CDayResponse")]
    string Get600CDay(string city, string format);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFWeatherService/GetCityWeather", ReplyAction="http://tempuri.org/IWCFWeatherService/GetCityWeatherResponse")]
    CS.DataModal.Entities.Weather GetCityWeather(string city);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWCFWeatherServiceChannel : IWCFWeatherService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WCFWeatherServiceClient : System.ServiceModel.ClientBase<IWCFWeatherService>, IWCFWeatherService
{
    
    public WCFWeatherServiceClient()
    {
    }
    
    public WCFWeatherServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WCFWeatherServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFWeatherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFWeatherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public CS.DataModal.Entities.Weather GetWeather(string ip)
    {
        return base.Channel.GetWeather(ip);
    }
    
    public string Get600CDay(string city, string format)
    {
        return base.Channel.Get600CDay(city, format);
    }
    
    public CS.DataModal.Entities.Weather GetCityWeather(string city)
    {
        return base.Channel.GetCityWeather(city);
    }
}
