//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace BD.Jcbg.Service.JyJzqyWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InterfaceServiceSoap", Namespace="http://tempuri.org/")]
    public partial class InterfaceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SynProjectInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelProjectInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePeopleInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpLoadDataListOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpLoadDataListPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectUpdateDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIteminfoUpdateDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrderStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataReocrdPhotoUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataReocrdPhotoBase64OperationCompleted;
        
        private System.Threading.SendOrPostCallback RelievePeopleStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InterfaceService() {
            this.Url = global::BD.Jcbg.Service.Properties.Settings.Default.BD_Jcbg_Service_JyJzqyWebService_InterfaceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SynProjectInfoCompletedEventHandler SynProjectInfoCompleted;
        
        /// <remarks/>
        public event DelProjectInfoCompletedEventHandler DelProjectInfoCompleted;
        
        /// <remarks/>
        public event UpdatePeopleInfoCompletedEventHandler UpdatePeopleInfoCompleted;
        
        /// <remarks/>
        public event UpLoadDataListCompletedEventHandler UpLoadDataListCompleted;
        
        /// <remarks/>
        public event UpLoadDataListPageCompletedEventHandler UpLoadDataListPageCompleted;
        
        /// <remarks/>
        public event GetProjectUpdateDataCompletedEventHandler GetProjectUpdateDataCompleted;
        
        /// <remarks/>
        public event GetIteminfoUpdateDataCompletedEventHandler GetIteminfoUpdateDataCompleted;
        
        /// <remarks/>
        public event UpdateOrderStatusCompletedEventHandler UpdateOrderStatusCompleted;
        
        /// <remarks/>
        public event GetDataReocrdPhotoUrlCompletedEventHandler GetDataReocrdPhotoUrlCompleted;
        
        /// <remarks/>
        public event GetDataReocrdPhotoBase64CompletedEventHandler GetDataReocrdPhotoBase64Completed;
        
        /// <remarks/>
        public event RelievePeopleStatusCompletedEventHandler RelievePeopleStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynProjectInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SynProjectInfo(string projectnum, string projectname, string constractionunit, string inspectunit, string slpeoplejson, string spnpeoplejson, string createunit) {
            object[] results = this.Invoke("SynProjectInfo", new object[] {
                        projectnum,
                        projectname,
                        constractionunit,
                        inspectunit,
                        slpeoplejson,
                        spnpeoplejson,
                        createunit});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SynProjectInfoAsync(string projectnum, string projectname, string constractionunit, string inspectunit, string slpeoplejson, string spnpeoplejson, string createunit) {
            this.SynProjectInfoAsync(projectnum, projectname, constractionunit, inspectunit, slpeoplejson, spnpeoplejson, createunit, null);
        }
        
        /// <remarks/>
        public void SynProjectInfoAsync(string projectnum, string projectname, string constractionunit, string inspectunit, string slpeoplejson, string spnpeoplejson, string createunit, object userState) {
            if ((this.SynProjectInfoOperationCompleted == null)) {
                this.SynProjectInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynProjectInfoOperationCompleted);
            }
            this.InvokeAsync("SynProjectInfo", new object[] {
                        projectnum,
                        projectname,
                        constractionunit,
                        inspectunit,
                        slpeoplejson,
                        spnpeoplejson,
                        createunit}, this.SynProjectInfoOperationCompleted, userState);
        }
        
        private void OnSynProjectInfoOperationCompleted(object arg) {
            if ((this.SynProjectInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SynProjectInfoCompleted(this, new SynProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelProjectInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DelProjectInfo(string projectnum) {
            object[] results = this.Invoke("DelProjectInfo", new object[] {
                        projectnum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DelProjectInfoAsync(string projectnum) {
            this.DelProjectInfoAsync(projectnum, null);
        }
        
        /// <remarks/>
        public void DelProjectInfoAsync(string projectnum, object userState) {
            if ((this.DelProjectInfoOperationCompleted == null)) {
                this.DelProjectInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelProjectInfoOperationCompleted);
            }
            this.InvokeAsync("DelProjectInfo", new object[] {
                        projectnum}, this.DelProjectInfoOperationCompleted, userState);
        }
        
        private void OnDelProjectInfoOperationCompleted(object arg) {
            if ((this.DelProjectInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelProjectInfoCompleted(this, new DelProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePeopleInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdatePeopleInfo(string peopleNo, string peoplename, string peopletype) {
            object[] results = this.Invoke("UpdatePeopleInfo", new object[] {
                        peopleNo,
                        peoplename,
                        peopletype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePeopleInfoAsync(string peopleNo, string peoplename, string peopletype) {
            this.UpdatePeopleInfoAsync(peopleNo, peoplename, peopletype, null);
        }
        
        /// <remarks/>
        public void UpdatePeopleInfoAsync(string peopleNo, string peoplename, string peopletype, object userState) {
            if ((this.UpdatePeopleInfoOperationCompleted == null)) {
                this.UpdatePeopleInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePeopleInfoOperationCompleted);
            }
            this.InvokeAsync("UpdatePeopleInfo", new object[] {
                        peopleNo,
                        peoplename,
                        peopletype}, this.UpdatePeopleInfoOperationCompleted, userState);
        }
        
        private void OnUpdatePeopleInfoOperationCompleted(object arg) {
            if ((this.UpdatePeopleInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePeopleInfoCompleted(this, new UpdatePeopleInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpLoadDataList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpLoadDataList(string projectnum, string gcbw, string itemcode, string starttime, string endtime, string syynum, string jzynum, string recordid, string qrcode, int orderstatus) {
            object[] results = this.Invoke("UpLoadDataList", new object[] {
                        projectnum,
                        gcbw,
                        itemcode,
                        starttime,
                        endtime,
                        syynum,
                        jzynum,
                        recordid,
                        qrcode,
                        orderstatus});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpLoadDataListAsync(string projectnum, string gcbw, string itemcode, string starttime, string endtime, string syynum, string jzynum, string recordid, string qrcode, int orderstatus) {
            this.UpLoadDataListAsync(projectnum, gcbw, itemcode, starttime, endtime, syynum, jzynum, recordid, qrcode, orderstatus, null);
        }
        
        /// <remarks/>
        public void UpLoadDataListAsync(string projectnum, string gcbw, string itemcode, string starttime, string endtime, string syynum, string jzynum, string recordid, string qrcode, int orderstatus, object userState) {
            if ((this.UpLoadDataListOperationCompleted == null)) {
                this.UpLoadDataListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpLoadDataListOperationCompleted);
            }
            this.InvokeAsync("UpLoadDataList", new object[] {
                        projectnum,
                        gcbw,
                        itemcode,
                        starttime,
                        endtime,
                        syynum,
                        jzynum,
                        recordid,
                        qrcode,
                        orderstatus}, this.UpLoadDataListOperationCompleted, userState);
        }
        
        private void OnUpLoadDataListOperationCompleted(object arg) {
            if ((this.UpLoadDataListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpLoadDataListCompleted(this, new UpLoadDataListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpLoadDataListPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpLoadDataListPage(
                    string projectnum, 
                    string gcbw, 
                    string itemcode, 
                    string starttime, 
                    string endtime, 
                    string jstarttime, 
                    string jendtime, 
                    string syynum, 
                    string jzynum, 
                    string syyname, 
                    string jzyname, 
                    string recordid, 
                    string qrcode, 
                    int orderstatus, 
                    int page, 
                    int limit) {
            object[] results = this.Invoke("UpLoadDataListPage", new object[] {
                        projectnum,
                        gcbw,
                        itemcode,
                        starttime,
                        endtime,
                        jstarttime,
                        jendtime,
                        syynum,
                        jzynum,
                        syyname,
                        jzyname,
                        recordid,
                        qrcode,
                        orderstatus,
                        page,
                        limit});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpLoadDataListPageAsync(
                    string projectnum, 
                    string gcbw, 
                    string itemcode, 
                    string starttime, 
                    string endtime, 
                    string jstarttime, 
                    string jendtime, 
                    string syynum, 
                    string jzynum, 
                    string syyname, 
                    string jzyname, 
                    string recordid, 
                    string qrcode, 
                    int orderstatus, 
                    int page, 
                    int limit) {
            this.UpLoadDataListPageAsync(projectnum, gcbw, itemcode, starttime, endtime, jstarttime, jendtime, syynum, jzynum, syyname, jzyname, recordid, qrcode, orderstatus, page, limit, null);
        }
        
        /// <remarks/>
        public void UpLoadDataListPageAsync(
                    string projectnum, 
                    string gcbw, 
                    string itemcode, 
                    string starttime, 
                    string endtime, 
                    string jstarttime, 
                    string jendtime, 
                    string syynum, 
                    string jzynum, 
                    string syyname, 
                    string jzyname, 
                    string recordid, 
                    string qrcode, 
                    int orderstatus, 
                    int page, 
                    int limit, 
                    object userState) {
            if ((this.UpLoadDataListPageOperationCompleted == null)) {
                this.UpLoadDataListPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpLoadDataListPageOperationCompleted);
            }
            this.InvokeAsync("UpLoadDataListPage", new object[] {
                        projectnum,
                        gcbw,
                        itemcode,
                        starttime,
                        endtime,
                        jstarttime,
                        jendtime,
                        syynum,
                        jzynum,
                        syyname,
                        jzyname,
                        recordid,
                        qrcode,
                        orderstatus,
                        page,
                        limit}, this.UpLoadDataListPageOperationCompleted, userState);
        }
        
        private void OnUpLoadDataListPageOperationCompleted(object arg) {
            if ((this.UpLoadDataListPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpLoadDataListPageCompleted(this, new UpLoadDataListPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProjectUpdateData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetProjectUpdateData(string projectnum) {
            object[] results = this.Invoke("GetProjectUpdateData", new object[] {
                        projectnum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectUpdateDataAsync(string projectnum) {
            this.GetProjectUpdateDataAsync(projectnum, null);
        }
        
        /// <remarks/>
        public void GetProjectUpdateDataAsync(string projectnum, object userState) {
            if ((this.GetProjectUpdateDataOperationCompleted == null)) {
                this.GetProjectUpdateDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectUpdateDataOperationCompleted);
            }
            this.InvokeAsync("GetProjectUpdateData", new object[] {
                        projectnum}, this.GetProjectUpdateDataOperationCompleted, userState);
        }
        
        private void OnGetProjectUpdateDataOperationCompleted(object arg) {
            if ((this.GetProjectUpdateDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectUpdateDataCompleted(this, new GetProjectUpdateDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetIteminfoUpdateData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetIteminfoUpdateData(string recordId) {
            object[] results = this.Invoke("GetIteminfoUpdateData", new object[] {
                        recordId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetIteminfoUpdateDataAsync(string recordId) {
            this.GetIteminfoUpdateDataAsync(recordId, null);
        }
        
        /// <remarks/>
        public void GetIteminfoUpdateDataAsync(string recordId, object userState) {
            if ((this.GetIteminfoUpdateDataOperationCompleted == null)) {
                this.GetIteminfoUpdateDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIteminfoUpdateDataOperationCompleted);
            }
            this.InvokeAsync("GetIteminfoUpdateData", new object[] {
                        recordId}, this.GetIteminfoUpdateDataOperationCompleted, userState);
        }
        
        private void OnGetIteminfoUpdateDataOperationCompleted(object arg) {
            if ((this.GetIteminfoUpdateDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIteminfoUpdateDataCompleted(this, new GetIteminfoUpdateDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrderStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateOrderStatus(string[] recordList, int orderstatus, string ordernum) {
            object[] results = this.Invoke("UpdateOrderStatus", new object[] {
                        recordList,
                        orderstatus,
                        ordernum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrderStatusAsync(string[] recordList, int orderstatus, string ordernum) {
            this.UpdateOrderStatusAsync(recordList, orderstatus, ordernum, null);
        }
        
        /// <remarks/>
        public void UpdateOrderStatusAsync(string[] recordList, int orderstatus, string ordernum, object userState) {
            if ((this.UpdateOrderStatusOperationCompleted == null)) {
                this.UpdateOrderStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateOrderStatus", new object[] {
                        recordList,
                        orderstatus,
                        ordernum}, this.UpdateOrderStatusOperationCompleted, userState);
        }
        
        private void OnUpdateOrderStatusOperationCompleted(object arg) {
            if ((this.UpdateOrderStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderStatusCompleted(this, new UpdateOrderStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataReocrdPhotoUrl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDataReocrdPhotoUrl(string recordId) {
            object[] results = this.Invoke("GetDataReocrdPhotoUrl", new object[] {
                        recordId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataReocrdPhotoUrlAsync(string recordId) {
            this.GetDataReocrdPhotoUrlAsync(recordId, null);
        }
        
        /// <remarks/>
        public void GetDataReocrdPhotoUrlAsync(string recordId, object userState) {
            if ((this.GetDataReocrdPhotoUrlOperationCompleted == null)) {
                this.GetDataReocrdPhotoUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataReocrdPhotoUrlOperationCompleted);
            }
            this.InvokeAsync("GetDataReocrdPhotoUrl", new object[] {
                        recordId}, this.GetDataReocrdPhotoUrlOperationCompleted, userState);
        }
        
        private void OnGetDataReocrdPhotoUrlOperationCompleted(object arg) {
            if ((this.GetDataReocrdPhotoUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataReocrdPhotoUrlCompleted(this, new GetDataReocrdPhotoUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataReocrdPhotoBase64", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDataReocrdPhotoBase64(string recordId) {
            object[] results = this.Invoke("GetDataReocrdPhotoBase64", new object[] {
                        recordId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataReocrdPhotoBase64Async(string recordId) {
            this.GetDataReocrdPhotoBase64Async(recordId, null);
        }
        
        /// <remarks/>
        public void GetDataReocrdPhotoBase64Async(string recordId, object userState) {
            if ((this.GetDataReocrdPhotoBase64OperationCompleted == null)) {
                this.GetDataReocrdPhotoBase64OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataReocrdPhotoBase64OperationCompleted);
            }
            this.InvokeAsync("GetDataReocrdPhotoBase64", new object[] {
                        recordId}, this.GetDataReocrdPhotoBase64OperationCompleted, userState);
        }
        
        private void OnGetDataReocrdPhotoBase64OperationCompleted(object arg) {
            if ((this.GetDataReocrdPhotoBase64Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataReocrdPhotoBase64Completed(this, new GetDataReocrdPhotoBase64CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RelievePeopleStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RelievePeopleStatus(string peoplenum) {
            object[] results = this.Invoke("RelievePeopleStatus", new object[] {
                        peoplenum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RelievePeopleStatusAsync(string peoplenum) {
            this.RelievePeopleStatusAsync(peoplenum, null);
        }
        
        /// <remarks/>
        public void RelievePeopleStatusAsync(string peoplenum, object userState) {
            if ((this.RelievePeopleStatusOperationCompleted == null)) {
                this.RelievePeopleStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRelievePeopleStatusOperationCompleted);
            }
            this.InvokeAsync("RelievePeopleStatus", new object[] {
                        peoplenum}, this.RelievePeopleStatusOperationCompleted, userState);
        }
        
        private void OnRelievePeopleStatusOperationCompleted(object arg) {
            if ((this.RelievePeopleStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RelievePeopleStatusCompleted(this, new RelievePeopleStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SynProjectInfoCompletedEventHandler(object sender, SynProjectInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SynProjectInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SynProjectInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DelProjectInfoCompletedEventHandler(object sender, DelProjectInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelProjectInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelProjectInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdatePeopleInfoCompletedEventHandler(object sender, UpdatePeopleInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePeopleInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePeopleInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpLoadDataListCompletedEventHandler(object sender, UpLoadDataListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpLoadDataListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpLoadDataListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpLoadDataListPageCompletedEventHandler(object sender, UpLoadDataListPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpLoadDataListPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpLoadDataListPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetProjectUpdateDataCompletedEventHandler(object sender, GetProjectUpdateDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectUpdateDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectUpdateDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetIteminfoUpdateDataCompletedEventHandler(object sender, GetIteminfoUpdateDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIteminfoUpdateDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIteminfoUpdateDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateOrderStatusCompletedEventHandler(object sender, UpdateOrderStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrderStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrderStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetDataReocrdPhotoUrlCompletedEventHandler(object sender, GetDataReocrdPhotoUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataReocrdPhotoUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataReocrdPhotoUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetDataReocrdPhotoBase64CompletedEventHandler(object sender, GetDataReocrdPhotoBase64CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataReocrdPhotoBase64CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataReocrdPhotoBase64CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RelievePeopleStatusCompletedEventHandler(object sender, RelievePeopleStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RelievePeopleStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RelievePeopleStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591